version: '3.8'
services:
  postgress:
    image: "postgres"
    container_name: postgresdb
    ports:
      - "5432:5432"
    volumes:
      - postgressdb_data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=password
    
  backend:
    build: .
    container_name: backend_app
    ports:
      - 3333:3333
    environment:
      POSTGRES_URL : "postgress://postgresdb:5432"
    volumes:
      - mount-dev:/src

volumes:
  postgressdb_data:
  mount-dev: